using System;
using System.Collections.Generic;
using System.Text;

namespace RCPServer
{
    public enum LanguageString
    {
        Weapon = 0,
        Armour = 1,
        Ring = 2,
        Amulet = 3,
        Potion = 4,
        Ingredient = 5,
        Image = 6,
        Miscellaneous = 7,
        OneHanded = 8,
        TwoHanded = 9,
        Ranged = 10,
        XHasJoinedParty = 11,
        YouHaveJoinedParty = 12,
        CouldNotJoinParty = 13,
        PartyInvite = 14,
        PartyInviteInstruction = 15,
        CouldNotInviteParty = 16,
        TradeInvite = 17,
        TradeInviteInstruction = 18,
        XIsOffline = 19,
        PlayerNotFound = 20,
        PlayersInGame = 21,
        PlayersInZone = 22,
        Season = 23,
        AbilityNotRecharged = 24,
        Ignoring = 25,
        UnIgnoring = 26,

        SKick = 27,
        SUnIgnore = 28,
        SIgnore = 29,
        SNetDump = 30,
        SPet = 31,
        SLeave = 32,
        SOk = 33,
        SInvite = 34,
        SXP = 35,
        SGold = 36,
        SSetAttribute = 37,
        SSetAttributeMax = 38,
        SScript = 39,
        SMe = 40,
        SYell = 41,
        SGM = 42,
        SG = 43,
        SP = 44,
        SPM = 45,
        STrade = 46,
        SAllPlayers = 47,
        SPlayers = 48,
        SWarp = 49,
        SWarpOther = 50,
        SAbility = 51,
        SGive = 52,
        SWeather = 53,
        STime = 54,
        SDate = 55,
        SSeason = 56,

        CriticalDamage = 57,
        WeaponDamaged = 58
    }
}
